%Subject

subject('I','yo').
subject('you','tu').
subject('he','el').
subject('she','ella').
subject('we','nosotros(as)').
subject('you','vosotros(as)').
subject('they','ellos(as)').

%----------------------------------------------------------------%

art('the','el').
art('the','la').
art('the','los').
art('the','las').
art('a','un').
art('a','una').
art('some','unos').
art('some','unas').

%----------------------------------------------------------------%

%%Object
%object('area','area').
%object('areas','areas').
%object('book','libro').
%object('books','libros').
%object('business','negocio').
%object('businesses','negocios').
%object('case','caso').
%object('cases','casos').
%object('child','niño').
%object('children','niños').
%object('company', 'compañia').
%object('companies','comapñias').
%object('country','pais').
%object('countries','paises').
%object('day','día').
%object('days','dias').
%object('eye','ojo').
%object('eyes','ojos').
%object('fact','hecho').
%object('facts','hechos').
%object('family','familia').
%object('families','familias').
%object('government','gobierno').
%object('goverments','gobiernos').
%object('group','grupo').
%object('groups','grupos').
%object('hand','mano').
%object('hands','manos').
%object('home','hogar').
%object('homes','hogares').
%object('job','trabajo').
%object('jobs','trabajos').
%object('life','vida').
%object('lifes','vidas').
%object('lot','mucho').%adjetivo
%object('lots','muchos').%adjetivo
%object('man','hombre').
%object('men','hombres').
%object('money','dinero').
%object('month','mes').
%object('months','meses').
%object('mother','madre').
%object('mothers','madres').
%object('sir','señor').
%object('sirs','señors').
%object('night','noche').
%object('nights','noches').
%object('number','numeros').
%object('numbers','numbers').
%object('part','partes').
%object('parts','partes').
%object('person','persona').
%object('people','personas').
%object('place','lugar').
%object('places','lugares').
%object('point','punto').
%object('points','puntos').
%object('problem','problema').
%object('problems','problemas').
%object('program','programa').
%object('question','pregunta').
%object('questions','preguntas').
%object('programs','programas').
%object('right','derecho').
%object('rights','derechos').
%object('left','izquierda').
%object('room','habitación').
%object('rooms','habitaciones').
%object('school','escuela').
%object('schools','escuelas').
%object('state','estado').
%object('states','estados').
%object('story','historia').
%object('stories','historias').
%object('student','estudiante').
%object('students','estudiantes').
%object('study','estudio').
%object('sudies','estudios').
%object('system','sistema').
%object('systems','sistemas').
%object('thing','cosa').
%object('time','tiempo').
%object('times','tiempos').
%object('water','agua').
%object('way','camino').
%object('ways','caminos').
%object('week','semana').
%object('weeks','semanas').
%object('woman','mujer').
%object('women','mujeres').
%object('word','palabra').
%object('words','words').
%object('work','trabajo').
%object('works','trabajos').
%object('world','mundo').
%object('worlds','mundos').
%object('year','año').
%object('years','años').

%---------------------------------------------------------------%

%simple_present_verb

present_verb('ask','pedir').
present_verb('be','ser').
present_verb('become','volverse').
present_verb('begin','empezar').
present_verb('call','llamar').
present_verb('can','poder').
present_verb('come','venir').
present_verb('do','hacer').
present_verb('feel','sentir').
present_verb('find','encontrar').
present_verb('get','obtener').
present_verb('give','dar').
present_verb('go','ir').
present_verb('have','tener').
present_verb('hear','escuchar').
present_verb('help','ayudar').
present_verb('keep','mantener').
present_verb('know','saber').
present_verb('leave','salir').
present_verb('let','dejar').
present_verb('like','gustar').
present_verb('live','vivir').
present_verb('look','mirar').
present_verb('to love','amar').
present_verb('to hate','odiar').
present_verb('make','hacer').
present_verb('may','poder').
present_verb('mean','significar').
present_verb('might','podría').
present_verb('must','deber').
present_verb('move','mover').
present_verb('need','necesitar').
present_verb('play','jugar').
present_verb('put','poner').
present_verb('run','correr').
present_verb('say','decir').
present_verb('see','ver').
present_verb('seem','parecer').
present_verb('show','mostrar').
present_verb('start','empezar').
present_verb('take','tomar').
present_verb('talk','hablar').
present_verb('tell','contar').
present_verb('think','pensar').
present_verb('try','intentar').
present_verb('trun','girar').
present_verb('use','usar').
present_verb('want','querer').
present_verb('work','trabajar').

%----------------------------------------------------------------%

%simple_past_verb


%----------------------------------------------------------------%

%core

oracion(S0,S,T0,T):- 
    sintagma_nominal(NUM,_,PERS,S0,S1,T0,T1),
    sintagma_verbal(NUM,_,PERS,S1,S,T1,T).

oracion(S0,S,T0,T):- 
    pronombre(NUM,GEN,PERS,S0,S1,T0,T1), 
    sintagma_verbal(NUM,GEN,PERS,S1,S,T1,T).

%---------------------------------------------------

sintagma_nominal(NUM,GEN,PERS,S0,S,T0,T):-
    determinante(NUM,GEN,PERS,S0,S1,T0,T1),
    nombre(NUM,GEN,S1,S,T1,T).

sintagma_nominal(NUM,GEN,PERS,S0,S,T0,T):-
    determinante(NUM,GEN,PERS,S0,S1,T0,T1),
    nombre(NUM,GEN,S1,S2,T2,T),
    adjetivo(NUM,GEN,S2,S,T1,T2).

%---------------------------------------------------------------

sintagma_verbal(NUM,_,PERS,S0,S,T0,T):-
    verbo(NUM,PERS,S0,S,T0,T).
sintagma_verbal(NUM,_,PERS,S0,S,T0,T):-
    verbo(NUM,PERS,S0,S1,T0,T1),
    sintagma_nominal(_,_,_,S1,S,T1,T).

%---------------------------------------------------------------

determinante(singular,masculino,tercera,['el'|S],S,['the'|T],T).
determinante(singular,femenino,tercera,['la'|S],S,['the'|T],T).
determinante(plural,masculino,tercera,['los'|S],S,['the'|T],T).
determinante(plural,femenino,tercera,['las'|S],S,['the'|T],T).

%---------------------------------------------------------------

nombre(singular,masculino,['hombre'|S],S,['man'|T],T).
nombre(plural,masculino,['hombres'|S],S,['men'|T],T).
nombre(singular,femenino,['manzana'|S],S,['apple'|T],T).
nombre(plural,femenino,['manzanas'|S],S,['apples'|T],T).
nombre(singular,femenino,['área'|S],S,['area'|T],T).
nombre(plural,femenino,['áreas'|S],S,['areas'|T],T).
nombre(singular,masculino,['libro'|S],S,['book'|T],T).
nombre(plural,masculino,['libros'|S],S,['books'|T],T).
nombre(singular,masculino,['negocio'|S],S,['business'|T],T).
nombre(plural,masculino,['negocios'|S],S,['businesses'|T],T).
nombre(singular,masculino,['caso'|S],S,['case'|T],T).
nombre(plural,masculino,['casos'|S],S,['cases'|T],T).
nombre(singular,masculino,['niño'|S],S,['children'|T],T).
nombre(singular,femenino,['niña'|S],S,['child'|T],T).
nombre(plural,masculino,['niños'|S],S,['children'|T],T).
nombre(plural,femenino,['niños'|S],S,['children'|T],T).
nombre(singular,femenino,['compañia'|S],S,['company'|T],T).
nombre(plural,femenino,['companiñas'|S],S,['companies'|T],T).
nombre(singular,masculino,['país'|S],S,['country'|T],T).
nombre(plural,masculino,['paises'|S],S,['countries'|T],T).
nombre(singular,masculino,['día'|S],S,['day'|T],T).
nombre(plural,masculino,['días'|S],S,['days'|T],T).
nombre(singular,masculino,['ojo'|S],S,['eye'|T],T).
nombre(plural,masculino,['ojos'|S],S,['eyes'|T],T).
nombre(singular,masculino,['hecho'|S],S,['fact'|T],T).
nombre(plural,masculino,['hechos'|S],S,['facts'|T],T).
nombre(singular,femenino,['familia'|S],S,['family'|T],T).
nombre(plural,femenino,['familias'|S],S,['families'|T],T).
nombre(singular,masculino,['gobierno'|S],S,['goverment'|T],T).
nombre(plural,masculino,['gobiernos'|S],S,['goverments'|T],T).
nombre(singular,masculino,['grupo'|S],S,['group'|T],T).
nombre(plural,masculino,['grupos'|S],S,['groups'|T],T).
nombre(singular,femenino,['mano'|S],S,['hand'|T],T).
nombre(plural,femenino,['manos'|S],S,['hands'|T],T).
nombre(singular,masculino,['hogar'|S],S,['home'|T],T).
nombre(plural,femenino,['hogares'|S],S,['homes'|T],T).
nombre(singular,masculino,['trabajo'|S],S,['job'|T],T).
nombre(plural,masculino,['trabajos'|S],S,['jobs'|T],T).
nombre(singular,femenino,['vida'|S],S,['life'|T],T).
nombre(plural,masculino,['vidas'|S],S,['lifes'|T],T).
nombre(singular,masculino,['dinero'|S],S,['money'|T],T).
nombre(singular,masculino,['mes'|S],S,['month'|T],T).
nombre(plural,masculino,['meses'|S],S,['months'|T],T).
nombre(singular,femenino,['madre'|S],S,['mother'|T],T).
nombre(plural,femenino,['madres'|S],S,['mothers'|T],T).
nombre(singular,masculino,['señor'|S],S,['sir'|T],T).
nombre(plural,masculino,['señores'|S],S,['sirs'|T],T).
nombre(singular,femenino,['noche'|S],S,['night'|T],T).
nombre(plural,femenino,['noches'|S],S,['nights'|T],T).
nombre(singular,masculino,['numero'|S],S,['number'|T],T).
nombre(plural,masculino,['numeros'|S],S,['numbers'|T],T).
nombre(singular,femenino,['parte'|S],S,['part'|T],T).
nombre(plural,femenino,['partes'|S],S,['parts'|T],T).
nombre(singular,femenino,['persona'|S],S,['person'|T],T).
nombre(plural,femenino,['personas'|S],S,['people'|T],T).
nombre(singular,masculino,['lugar'|S],S,['place'|T],T).
nombre(plural,femenino,['lugares'|S],S,['places'|T],T).
nombre(singular,masculino,['putno'|S],S,['point'|T],T).
nombre(plural,masculino,['puntos'|S],S,['points'|T],T).
nombre(singular,masculino,['problema'|S],S,['points'|T],T).
nombre(plural,masculino,['problemas'|S],S,['points'|T],T).
nombre(singular,masculino,['programa'|S],S,['program'|T],T).
nombre(plural,masculino,['programas'|S],S,['programs'|T],T).
nombre(singular,femenino,['pregunta'|S],S,['question'|T],T).
nombre(plural,femenino,['preguntas'|S],S,['questions'|T],T).
nombre(singular,masculino,['derecho'|S],S,['right'|T],T).
nombre(plural,masculino,['derechos'|S],S,['rights'|T],T).
nombre(singular,femenino,['izquierda'|S],S,['left'|T],T).
nombre(singular,femenino,['habitación'|S],S,['room'|T],T).
nombre(plural,femenino,['habitaciones'|S],S,['rooms'|T],T).
nombre(singular,femenino,['escuela'|S],S,['school'|T],T).
nombre(plural,femenino,['escuelas'|S],S,['schools'|T],T).
nombre(singular,masculino,['estado'|S],S,['state'|T],T).
nombre(plural,masculino,['estados'|S],S,['states'|T],T).
nombre(singular,femenino,['historia'|S],S,['story'|T],T).
nombre(plural,femenino,['historias'|S],S,['stories'|T],T).
nombre(singular,masculino,['estudiante'|S],S,['student'|T],T).
nombre(plural,masculino,['estudiantes'|S],S,['students'|T],T).
nombre(singular,masculino,['estudio'|S],S,['studio'|T],T).
nombre(plural,masculino,['estudios'|S],S,['studios'|T],T).
nombre(singular,masculino,['sistema'|S],S,['system'|T],T).
nombre(plural,masculino,['sistemas'|S],S,['systems'|T],T).
nombre(singular,femenino,['cosa'|S],S,['thing'|T],T).
nombre(plural,femenino,['cosas'|S],S,['things'|T],T).
nombre(singular,masculino,['tiempo'|S],S,['time'|T],T).
nombre(plural,masculino,['tiempos'|S],S,['times'|T],T).
nombre(singular,masculino,['agua'|S],S,['water'|T],T).
nombre(singular,masculino,['camino'|S],S,['way'|T],T).
nombre(plural,masculino,['caminos'|S],S,['ways'|T],T).
nombre(singular,femenino,['semana'|S],S,['week'|T],T).
nombre(plural,femenino,['semanas'|S],S,['weeks'|T],T).
nombre(singular,femenino,['mujer'|S],S,['woman'|T],T).
nombre(plural,femenino,['mujeres'|S],S,['woman'|T],T).
nombre(singular,femenino,['palabra'|S],S,['word'|T],T).
nombre(plural,femenino,['palabras'|S],S,['words'|T],T).
nombre(singular,masculino,['mundo'|S],S,['world'|T],T).
nombre(plural,masculino,['mundos'|S],S,['worlds'|T],T).
nombre(singular,masculino,['año'|S],S,['year'|T],T).
nombre(plural,masculino,['años'|S],S,['years'|T],T).

%---------------------------------------------------------------

verbo(singular,primera,['como'|S],S,['eat'|T],T).
verbo(plural,primera,['comemos'|S],S,['eat'|T],T).
verbo(singular,segunda,['comes'|S],S,['eat'|T],T).
verbo(plural,segunda,['comeis'|S],S,['eat'|T],T).
verbo(singular,tercera,['come'|S],S,['eats'|T],T).
verbo(plural,tercera,['comen'|S],S,['eat'|T],T).

%---------------------------------------------------------------

adjetivo(singular,masculino,['pequeño'|S],S,['little'|T],T).
adjetivo(singular,femenino,['pequeña'|S],S,['little'|T],T).
adjetivo(plural,masculino,['pequeños'|S],S,['little'|T],T).
adjetivo(plural,femenino,['pequeñas'|S],S,['little'|T],T).

%---------------------------------------------------------------

pronombre(singular,_,primera,['yo'|S],S,['I'|T],T).
pronombre(singular,_,segunda,['tu'|S],S,['you'|T],T).
pronombre(singular,masculino,tercera,['el'|S],S,['he'|T],T).
pronombre(singular,femenino,tercera,['ella'|S],S,['she'|T],T).
pronombre(plural,masculino,primera,['nosotros'|S],S,['we'|T],T).
pronombre(plural,masculino,segunda,['vosotros'|S],S,['you'|T],T).
pronombre(plural,masculino,tercera,['ellos'|S],S,['they'|T],T).
pronombre(plural,femenino,primera,['nosotras'|S],S,['we'|T],T).
pronombre(plural,femenino,segunda,['vosotras'|S],S,['you'|T],T).
pronombre(plural,femenino,tercera,['ellas'|S],S,['they'|T],T).
