%Subject

subject('I','yo').
subject('you','tu').
subject('he','el').
subject('she','ella').
subject('we','nosotros(as)').
subject('you','vosotros(as)').
subject('they','ellos(as)').

%----------------------------------------------------------------%

art('the','el').
art('the','la').
art('the','los').
art('the','las').
art('a','un').
art('a','una').
art('some','unos').
art('some','unas').

%----------------------------------------------------------------%

%Object
object('area','area').
object('areas','areas').
object('book','libro').
object('books','libros').
object('business','negocio').
object('businesses','negocios').
object('case','caso').
object('cases','casos').
object('child','niño').
object('children','niños').
object('company', 'compañia').
object('companies','comapñias').
object('country','pais').
object('countries','paises').
object('day','día').
object('days','dias').
object('eye','ojo').
object('eyes','ojos').
object('fact','hecho').
object('facts','hechos').
object('family','familia').
object('families','familias').
object('government','gobierno').
object('goverments','gobiernos').
object('group','grupo').
object('groups','grupos').
object('hand','mano').
object('hands','manos').
object('home','hogar').
object('homes','hogares').
object('job','trabajo').
object('jobs','trabajos').
object('life','vida').
object('lifes','vidas').
object('lot','mucho').
object('lots','muchos').
object('man','hombre').
object('men','hombres').
object('money','dinero').
object('month','mes').
object('months','meses').
object('mother','madre').
object('mothers','madres').
object('sir','señor').
object('sirs','señors').
object('night','noche').
object('nights','noches').
object('number','numeros').
object('numbers','numbers').
object('part','partes').
object('parts','partes').
object('person','persona').
object('people','personas').
object('place','lugar').
object('places','lugares').
object('point','punto').
object('points','puntos').
object('problem','problema').
object('problems','problemas').
object('program','programa').
object('question','pregunta').
object('questions','preguntas').
object('program','programs').
object('right','derecho').
object('rights','derechos').
object('left','izquierda').
object('room','habitación').
object('rooms','habitaciones').
object('school','escuela').
object('schools','escuelas').
object('state','estado').
object('states','estados').
object('story','historia').
object('stories','historias').
object('student','estudiante').
object('students','estudiantes').
object('study','estudio').
object('sudies','estudios').
object('system','sistema').
object('systems','sistemas').
object('thing','cosa').
object('time','tiempo').
object('times','tiempos').
object('water','agua').
object('way','camino').
object('ways','caminos').
object('week','semana').
object('weeks','semanas').
object('woman','mujer').
object('women','mujeres').
object('word','palabra').
object('words','words').
object('work','trabajo').
object('works','trabajos').
object('world','mundo').
object('worlds','mundos').
object('year','año').
object('years','años').

%---------------------------------------------------------------%

%simple_present_verb

present_verb('ask','pedir').
present_verb('be','ser').
present_verb('become','volverse').
present_verb('begin','empezar').
present_verb('call','llamar').
present_verb('can','poder').
present_verb('come','venir').
present_verb('do','hacer').
present_verb('feel','sentir').
present_verb('find','encontrar').
present_verb('get','obtener').
present_verb('give','dar').
present_verb('go','ir').
present_verb('have','tener').
present_verb('hear','escuchar').
present_verb('help','ayudar').
present_verb('keep','mantener').
present_verb('know','saber').
present_verb('leave','salir').
present_verb('let','dejar').
present_verb('like','gustar').
present_verb('live','vivir').
present_verb('look','mirar').
present_verb('to love','amar').
present_verb('to hate','odiar').
present_verb('make','hacer').
present_verb('may','poder').
present_verb('mean','significar').
present_verb('might','podría').
present_verb('must','deber').
present_verb('move','mover').
present_verb('need','necesitar').
present_verb('play','jugar').
present_verb('put','poner').
present_verb('run','correr').
present_verb('say','decir').
present_verb('see','ver').
present_verb('seem','parecer').
present_verb('show','mostrar').
present_verb('start','empezar').
present_verb('take','tomar').
present_verb('talk','hablar').
present_verb('tell','contar').
present_verb('think','pensar').
present_verb('try','intentar').
present_verb('trun','girar').
present_verb('use','usar').
present_verb('want','querer').
present_verb('work','trabajar').

%----------------------------------------------------------------%

