%Subject

subject(i, yo).
subject(you, tu).
subject(he, el).
subject(she, ella).
subject(you, usted).
subject(we, nosotros).
subject(we, nosotras).
subject(you, vosotros).
subject(you, vosotras.
subject(they, ellos).
subject(they, ellas).

%------------------------------------------------------------------------%

%Object

object(angle, angulo).
object(ant, hormiga).
object(apple, manzana).
object(arch, arco).
object(arm, brazo).
object(amry, ejercito).
object(baby, bebe).
object(bag, bolso).
object(ball, bola).
object(band, banda).
object(bath, baño).
object(bed, cama).
object(bee, abeja).
object(bell, campana).
object(berry, baya).
object(bird, pajaro).
object(blade, cuchilla).
object(board, tabla).
object(boat, bote).
object(bone, hueso).
object(book, libro).
object(boot, bota).
object(bottle, botella).
object(box, caja).
object(boy, hombre).
object(brain cerebro).
object(branch, rama).
object(brick, ladrillo).
object(brush, cepillo).
object(button, botón).
object(cake, queque).
object(camera, cámara).
object(card, carta).
object(car, carro).
object(chain, cadena).
object(cheese, queso).
object(chest, pecho).
object(chin, barbilla).
object(church, iglesia).
object(circle, circulo).
object(clock, reloj).
object(cloud, nube).
object(cow, vaca).
object(cup, vaso).
object(dog, perro).
object(door, puerta).
object(dress, vestido).
object(ear, oreja).
object(egg, huevo).
object(engine, motor).
object(eye, ojo).
object(face, cara).
object(farm, granja).
object(feather, pluma).
object(finger, dedo).
object(fish, pez).
object(flag, bandera).
object(floor, piso).
object(foot, pie).
object(fork, tenedor).
object(garden, patio).
object(girl, mujer).
object(glove, guante).
object(goat, cabra).
object(gun, pistola).
object(hair, pelo).
object(hammer, martillo).
object(hand, mano).
object(hat, sombrero).
object(head, cabeza).
object(heart, corazón).
object(horse, caballo).
object(hospital, hospital).
object(house, casa).
object(island, isla).
object(jewel, joya).
object(key, llave).
