
oracion(S0,S,T0,T):- sintagma_nominal(NUM,_,PERS,S0,S1,T0,T1),
sintagma_verbal(NUM,_,PERS,S1,S,T1,T).
oracion(S0,S,T0,T):- pronombre(NUM,GEN,PERS,S0,S1,T0,T1),
sintagma_verbal(NUM,GEN,PERS,S1,S,T1,T).
%---------------------------------------------------------------
sintagma_nominal(NUM,GEN,PERS,S0,S,T0,T):-
determinante(NUM,GEN,PERS,S0,S1,T0,T1),
 nombre(NUM,GEN,S1,S,T1,T).
sintagma_nominal(NUM,GEN,PERS,S0,S,T0,T):-
determinante(NUM,GEN,PERS,S0,S1,T0,T1),
 nombre(NUM,GEN,S1,S2,T2,T),
 adjetivo(NUM,GEN,S2,S,T1,T2).
%---------------------------------------------------------------
sintagma_verbal(NUM,_,PERS,S0,S,T0,T):-
verbo(NUM,PERS,S0,S,T0,T).
sintagma_verbal(NUM,_,PERS,S0,S,T0,T):-
verbo(NUM,PERS,S0,S1,T0,T1),
sintagma_nominal(_,_,_,S1,S,T1,T).

%---------------------------------------------------------------%
determinante(singular,masculino,tercera,['el'|S],S,['the'|T],T).
determinante(singular,femenino,tercera,['la'|S],S,['the'|T],T).
determinante(plural,masculino,tercera,['los'|S],S,['the'|T],T).
determinante(plural,femenino,tercera,['las'|S],S,['the'|T],T).
%---------------------------------------------------------------
nombre(singular,masculino,['hombre'|S],S,['man'|T],T).
nombre(plural,masculino,['hombres'|S],S,['men'|T],T).
nombre(singular,femenino,['manzana'|S],S,['apple'|T],T).
nombre(plural,femenino,['manzanas'|S],S,['apples'|T],T).
%---------------------------------------------------------------
verbo(singular,primera,['pido'|S],['ask'|S]).
verbo(singular,primera,['soy'|S],['am'|S]).
verbo(singular,primera,['vuelvo'|S],['become'|S]).
verbo(singular,primera,['comienzo'|S],['begin'|S]).
verbo(singular,primera,['llamo'|S],['call'|S]).
verbo(singular,primera,['puedo'|S],['can'|S]).
verbo(singular,primera,['vengo'|S],['come'|S]).
verbo(singular,primera,['hago'|S],['do'|S]).
verbo(singular,primera,['siento'|S],['feel'|S]).
verbo(singular,primera,['encuentro'|S],['find'|S]).
verbo(singular,primera,['obtengo'|S],['get'|S]).
verbo(singular,primera,['doy'|S],['give'|S]).
verbo(singular,primera,['voy'|S],['go'|S]).
verbo(singular,primera,['tengo'|S],['have'|S]).
verbo(singular,primera,['escucho'|S],['hear'|S]).
verbo(singular,primera,['ayudo'|S],['help'|S]).
verbo(singular,primera,['mantengo'|S],['keep'|S]).
verbo(singular,primera,['s�'|S],['know'|S]).
verbo(singular,primera,['salgo'|S],['leave'|S]).
verbo(singular,primera,['dejo'|S],['let'|S]).
verbo(singular,primera,['gustar'|S],['like'|S]).
verbo(singular,primera,['vivo'|S],['live'|S]).
verbo(singular,primera,['miro'|S],['look'|S]).
verbo(singular,primera,['amo'|S],['to love'|S]).
verbo(singular,primera,['odio'|S],['to hate'|S]).
verbo(singular,primera,['hago'|S],['make'|S]).
verbo(singular,primera,['puedo'|S],['may'|S]).
verbo(singular,primera,['significo'|S],['mean'|S]).
verbo(singular,primera,['debo'|S],['must'|S]).
verbo(singular,primera,['muevo'|S],['move'|S]).
verbo(singular,primera,['necesito'|S],['need'|S]).
verbo(singular,primera,['juego'|S],['play'|S]).
verbo(singular,tercera,['pone'|S],['puts'|S]).
verbo(singular,primera,['corro'|S],['run'|S]).
verbo(singular,primera,['digo'|S],['say'|S]).
verbo(singular,primera,['veo'|S],['see'|S]).
verbo(singular,primera,['parezco'|S],['seem'|S]).
verbo(singular,primera,['muestro'|S],['show'|S]).
verbo(singular,primera,['empiezo'|S],['start'|S]).
verbo(singular,primera,['tomo'|S],['take'|S]).
verbo(singular,primera,['hablo'|S],['talk'|S]).
verbo(singular,primera,['cuento'|S],['tell'|S]).
verbo(singular,primera,['pienso'|S],['think'|S]).
verbo(singular,primera,['intento'|S],['try'|S]).
verbo(singular,primera,['giro'|S],['trun'|S]).
verbo(singular,primera,['uso'|S],['use'|S]).
verbo(singular,primera,['quiero'|S],['want'|S]).
verbo(singular,primera,['trabajo'|S],['work'|S]).

verbo(singular,primera,['como'|S],S,['eat'|T],T).
verbo(plural,primera,['comemos'|S],S,['eat'|T],T).
verbo(singular,segunda,['comes'|S],S,['eat'|T],T).
verbo(plural,segunda,['comeis'|S],S,['eat'|T],T).
verbo(singular,tercera,['come'|S],S,['eats'|T],T).
verbo(plural,tercera,['comen'|S],S,['eat'|T],T).
%---------------------------------------------------------------
adjetivo(singular,masculino,['pequenyo'|S],S,['little'|T],T).
adjetivo(singular,femenino,['pequenya'|S],S,['little'|T],T).
adjetivo(plural,masculino,['pequenyos'|S],S,['little'|T],T).
adjetivo(plural,femenino,['pequenyas'|S],S,['little'|T],T).
%---------------------------------------------------------------
pronombre(singular,_,primera,['yo'|S],S,['i'|T],T).
pronombre(singular,_,segunda,['tu'|S],S,['you'|T],T).
pronombre(singular,masculino,tercera,['el'|S],S,['he'|T],T).
pronombre(singular,femenino,tercera,['ella'|S],S,['she'|T],T).
pronombre(plural,masculino,primera,['nosotros'|S],S,['we'|T],T).
pronombre(plural,masculino,segunda,['vosotros'|S],S,['you'|T],T).
pronombre(plural,masculino,tercera,['ellos'|S],S,['they'|T],T).
pronombre(plural,femenino,primera,['nosotras'|S],S,['we'|T],T).
pronombre(plural,femenino,segunda,['vosotras'|S],S,['you'|T],T).
pronombre(plural,femenino,tercera,['ellas'|S],S,['they'|T],T).
